#define WATCH_SCREEN_WIDTH 144
#define WATCH_SCREEN_HEIGHT 168

#define MATRIX_NUMBER_HORIZONTAL_TILES 19
#define MATRIX_NUMBER_VERTICAL_TILES 21
#define MATRIX_TILE_PIXEL_SIZE_W 8
#define MATRIX_TILE_PIXEL_SIZE_H 8
#define NUMBER_WIDTH_IN_TILES 3
#define NUMBER_HEIGHT_IN_TILES 10

#define SECONDS_IN_A_MINUTE 60
